checks:
    php:
        code_rating: true
tools:
    external_code_coverage:
        timeout: 600
    php_code_coverage: false
    php_code_sniffer:
        config:
            standard: PSR2
        filter:
            paths: ['src']
